import type { Page } from '../data/siteData'
import { industries, services } from '../data/siteData'
import { ExperienceMarquee, GoldDivider, Label } from '../components/ContentBits'
import { assets } from '../assets/assets'

export default function HomePage({ navigate }: { navigate: (page: Page) => void }) {
  return <main>
    <section className="relative flex h-screen items-end overflow-hidden pb-24"><div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: `url("${assets.heroBackground}")` }} /><div className="absolute inset-0 bg-gradient-to-t from-[#06060F]/95 via-[#06060F]/45 to-[#06060F]/20" /><div className="relative z-10 max-w-5xl px-8 md:px-14"><Label>Est. 1996 - Global Logistics & Consulting</Label><h1 className="mt-7 mb-8 text-5xl leading-[0.9] text-[#F0E8D5] md:text-7xl lg:text-[5.5rem]" style={{ fontFamily: "'Playfair Display', serif" }}>Navigating<br /><em className="text-[#C9A84C] not-italic">Complexity.</em><br />Delivering<br />Certainty.</h1><p className="mb-10 max-w-md text-[0.95rem] leading-relaxed text-[#8A8070]">Aurum provides integrated logistics management and strategic consulting to the world's most demanding industries.</p><div className="flex flex-wrap gap-4"><button onClick={() => navigate('services')} className="bg-[#C9A84C] px-8 py-3.5 text-[9px] font-bold font-mono tracking-[0.25em] text-[#0B0B14] uppercase hover:bg-[#E8C96A]">Our Services</button><button onClick={() => navigate('industries')} className="border border-[#C9A84C]/40 px-8 py-3.5 text-[9px] font-mono tracking-[0.25em] text-[#C9A84C] uppercase hover:bg-[#C9A84C]/10">Industries</button></div></div></section>
    <section className="border-y border-[#C9A84C]/10 bg-[#10101C] py-10"><div className="mx-auto grid max-w-6xl grid-cols-2 gap-6 px-8 md:grid-cols-4">{[['40+', 'Countries Served', 'Global network'], ['500+', 'Active Clients', 'Fortune 500 & above'], ['$12B', 'Cargo Managed', 'Annual freight value'], ['28', 'Years Operating', 'Since 1996']].map(([value, label, sub]) => <div key={label} className="border-r border-[#C9A84C]/10 px-4 text-center last:border-0"><div className="mb-1 text-[2.6rem] leading-none text-[#C9A84C]" style={{ fontFamily: "'Playfair Display', serif" }}>{value}</div><div className="text-[11px] font-mono text-[#F0E8D5]/70">{label}</div><div className="mt-0.5 text-[9px] font-mono text-[#8A8070]">{sub}</div></div>)}</div></section>
    <section className="mx-auto max-w-7xl px-8 py-28 md:px-14"><div className="grid items-center gap-16 lg:grid-cols-2"><div><Label>About iLogBC</Label><h2 className="mt-5 mb-4 text-[2.8rem] leading-tight text-[#F0E8D5] md:text-5xl" style={{ fontFamily: "'Playfair Display', serif" }}>Where Precision<br />Meets <em className="text-[#C9A84C]">Purpose</em></h2><GoldDivider /><p className="mt-6 mb-4 text-sm leading-relaxed text-[#8A8070]">Founded in New York in 1996, iLogBC has grown from a boutique freight forwarder into a fully integrated logistics and consulting firm operating across six continents.</p><p className="mb-8 text-sm leading-relaxed text-[#8A8070]">Our consultants and logistics engineers bring deep sector expertise, enabling interventions that are strategically coherent and operationally executable.</p><div className="flex flex-wrap gap-2.5">{['ISO 9001:2015', 'TAPA FSR A', 'GDP Certified', 'IATA CASS'].map((item) => <span key={item} className="border border-[#C9A84C]/25 px-3 py-1.5 text-[9px] font-mono tracking-wider text-[#C9A84C] uppercase">{item}</span>)}</div></div><div className="relative h-[400px] overflow-hidden border border-[#C9A84C]/20 bg-[#11111E]"><div className="absolute inset-8 border border-[#C9A84C]/20" /><div className="absolute left-10 top-10 h-px w-24 bg-[#C9A84C]" /><div className="absolute bottom-10 right-10 text-right"><div className="text-6xl text-[#C9A84C]/20" style={{ fontFamily: "'Playfair Display', serif" }}>28</div><div className="text-[9px] font-mono tracking-[0.2em] text-[#C9A84C] uppercase">Years of experience</div></div></div></div></section>
    <section className="border-y border-[#C9A84C]/10 bg-[#0D0D1A] px-8 py-20 md:px-14"><div className="mx-auto max-w-7xl"><Label>Core Offerings</Label><h2 className="mt-4 mb-12 text-[2.5rem] text-[#F0E8D5]" style={{ fontFamily: "'Playfair Display', serif" }}>What We Do</h2><div className="grid gap-px bg-[#C9A84C]/10 md:grid-cols-3">{services.slice(0, 3).map((service) => <button key={service.id} onClick={() => navigate('services')} className="bg-[#0D0D1A] p-9 text-left hover:bg-[#11111E]"><div className="mb-6 text-[9px] font-mono text-[#C9A84C]/40">{service.number}</div><h3 className="mb-3 text-xl text-[#F0E8D5]" style={{ fontFamily: "'Playfair Display', serif" }}>{service.name}</h3><p className="mb-7 text-[12px] leading-relaxed text-[#8A8070]">{service.short}</p><span className="text-[10px] font-mono text-[#C9A84C]">Learn more →</span></button>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-8 py-28 md:px-14"><div className="grid gap-14 lg:grid-cols-5"><div className="lg:col-span-2"><Label>Sectors</Label><h2 className="mt-5 mb-6 text-[2.8rem] leading-tight text-[#F0E8D5] md:text-5xl" style={{ fontFamily: "'Playfair Display', serif" }}>Industries<br /><em className="text-[#C9A84C]">Connected</em></h2><p className="mb-9 max-w-xs text-sm leading-relaxed text-[#8A8070]">We operate at the intersection of physical and financial flows across the world's most complex sectors.</p><button onClick={() => navigate('industries')} className="border border-[#C9A84C]/40 px-6 py-3 text-[9px] font-mono tracking-[0.22em] text-[#C9A84C] uppercase hover:bg-[#C9A84C]/10">View All Industries</button></div><div className="grid grid-cols-2 gap-3 lg:col-span-3">{industries.slice(0, 6).map(([name], index) => <button key={name} onClick={() => navigate('industries')} className="border border-[#C9A84C]/10 p-5 text-left hover:border-[#C9A84C]/45"><div className="mb-2 text-[9px] font-mono text-[#C9A84C]/40">0{index + 1}</div><div className="text-[13px] leading-snug text-[#F0E8D5]" style={{ fontFamily: "'Playfair Display', serif" }}>{name}</div></button>)}</div></div></section>
    <ExperienceMarquee />
    <section className="relative overflow-hidden border-t border-[#C9A84C]/10 bg-[#10101C] py-24 text-center"><div className="absolute inset-0 opacity-20" style={{ backgroundImage: 'linear-gradient(#C9A84C 1px, transparent 1px), linear-gradient(90deg, #C9A84C 1px, transparent 1px)', backgroundSize: '72px 72px' }} /><div className="relative z-10 mx-auto max-w-3xl px-8"><Label>Ready to Begin</Label><h2 className="mt-5 mb-6 text-[2.6rem] text-[#F0E8D5] md:text-5xl" style={{ fontFamily: "'Playfair Display', serif" }}>Let's Solve Your<br />Greatest Challenges</h2><p className="mx-auto mb-10 max-w-lg text-sm leading-relaxed text-[#8A8070]">Speak with one of our sector specialists to discover how iLogBC can transform your supply chain or strategic position.</p><button className="bg-[#C9A84C] px-10 py-4 text-[9px] font-bold font-mono tracking-[0.28em] text-[#0B0B14] uppercase hover:bg-[#E8C96A]">Schedule a Consultation</button></div></section>
  </main>
}
